name: Generate currentIssues.json

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,8,16 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-issue-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Checkout to branch
        run: git checkout ${{ env.branch }}
      - name: Commit & Push
        run: |
          set -x
          bun run generate-task
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'chore: update currentIssues.json lastUpdated.ts' --allow-empty
          git push origin ${{ env.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
